# Generated by Django 3.0.4 on 2021-01-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='CheckInTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='CheckOutTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='CheckedIn',
            field=models.BooleanField(default=False),
        ),
    ]
